language: csharp
mono: none
dotnet: 2.0.0
install:
  - cd ./AppscoreAncestry.Web/
  - npm install
  - cd ../
script:
  - dotnet restore
  - dotnet build 
  - dotnet test ./AppscoreAncestry.Tests/AppscoreAncestry.Domain.Tests/
  - dotnet test ./AppscoreAncestry.Tests/AppscoreAncestry.Infrastructure.Tests/